### ISSUE TITLE
Cors not enabled

### ISSUE THREAD

**Issue by Snickdx** [cheatsnake/emojihub#10]
Got a cors error when making a request to https://emojihub.yurace.pro/api/all/group/animal-bird in javascript of a page.

**Comment by cheatsnake** [comment]
> Got a cors error when making a request to https://emojihub.yurace.pro/api/all/group/animal-bird in javascript of a page.

Hello! Thanks for your feedback. I really forgot about the CORS configuration when I rewrote the application in Go. Now it [fixed](https://github.com/cheatsnake/emojihub/commit/247edfc039f89b6c2217d070dad8a8d69b041e53) and service are available for everyone.

Try it:
```js
const makeRequest = async () => {
  try {
    const resp = await fetch('https://emojihub.yurace.pro/api/all/group/animal-bird')
    console.log(await resp.json())
  } catch (error) {
    console.log(error);
  }
};

makeRequest();
```

**Comment by Snickdx** [comment]
Awesome! Cheers my dude!
