### ISSUE TITLE
Heroku application error

### ISSUE THREAD

**Issue by trixie7** [cheatsnake/emojihub#4]
I want to access the emoji data but am unable to - when I copy paste the given urls like https://emojihub.herokuapp.com/api/random/group_face_positive into my browser and search I get the following message: "An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail"

**Comment by cheatsnake** [comment]
> I want to access the emoji data but am unable to - when I copy paste the given urls like https://emojihub.herokuapp.com/api/random/group_face_positive into my browser and search I get the following message: "An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command heroku logs --tail"

Sorry, my Heroku account has a month limit for hosting apps. The app will be working again next week, June 1.
