### ISSUE TITLE
Using emojihub in a student project

### ISSUE THREAD

**Issue by Pistus** [cheatsnake/emojihub#8]
Hi @cheatsnake - one of our teachers at scrimba.com wants to use your api in a project she is building for students. For public api's I prefer that we host our own version for students it since it is not uncommon for public api's to change domains, path structure to change in versions, they go down etc. which creates issues for our recorded material. This also reduces the traffic from your heroku instance.

Happy to put in canonical url tags,etc. to give you any seo,etc. Feel free to reach out on frode at scrimba to discuss as well.

**Comment by cheatsnake** [comment]
> Hi @cheatsnake - one of our teachers at scrimba.com wants to use your api in a project she is building for students. For public api's I prefer that we host our own version for students it since it is not uncommon for public api's to change domains, path structure to change in versions, they go down etc. which creates issues for our recorded material. This also reduces the traffic from your heroku instance.
> 
> Happy to put in canonical url tags,etc. to give you any seo,etc. Feel free to reach out on frode at scrimba to discuss as well.

Dear @Pistus - Thank you for your feedback, I am very happy that EmojiHub API is useful for someone. EmojiHub is an open-source project, so of course you can freely and without restrictions use the source code of the application for your purposes.

As for the reliability and immutability of API endpoints of open-source projects, you're right. Unfortunately, not everyone can guarantee such requirements.

A similar situation is likely to happen with EmojiHub. The fact is that Heroku service will very soon close its free application hosting plan, on which EmojiHub works. Therefore, we will move to another hosting with a new domain name, with some changes in the API endpoints.

Also in the next few days the application will be rewritten in Go. Emphasis will be placed on a simpler code base and not using an external database. This will make it very easy and fast to run your own clones of the application, for example using a Docker container or a pre-built binary file.

**Comment by Pistus** [comment]
That sounds all great and a good structure for an open api. I will then probably wait to see the new structure.

At the moment the data is not included, do you intend to include the data as well in new version?

**Comment by cheatsnake** [comment]
> That sounds all great and a good structure for an open api. I will then probably wait to see the new structure.
> 
> At the moment the data is not included, do you intend to include the data as well in new version?

You can already use the new version to run your own clones - https://github.com/cheatsnake/emojihub/tree/go-version
The readme file describes step by step how to start the server.

Very soon it will be launched on a new domain.
